services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=DorAm1994
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=password
    command: npm run dev
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DorAm1994
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
